tutorme:
  superusers:
    - barbuzaster@gmail.com
    - asteegs@gmail.com
    - vadympetrychenko@gmail.com
  superuserDefaultPassword: qwe123qwe

django:
  awsS3Enabled: no
  debug: true
  cache: true
  elasticacheLocation:
  elasticsearchHost: 127.0.0.1:9200
  elasticacheQueue:
  host: no
  staticRoot: $basedir/static
  mediaUrl: /media/
  mediaRoot: $basedir/media

email:
  careers: careers@tutorme.com
  press: press@tutorme.com

facebook:
  id: fake-id
  secret: fake-secret

mandrill:
  key: 2ElR16HitKh45teRtakoyQ
  from: 'TutorMe dev robot <robot@tutorme.local>'

firebase:
  secret: iMCKsqk3sSw8D3WqTBXacqV2tDtk9nJshEeiVzuC

opentok:
  secret: 3ad45785df51ed011818f157467f3b53c91885b8

postgres:
  url: postgres://tutor:tutor@127.0.0.1/tutor

stripe:
  secret: sk_test_ACASWuXE2y3X4MDH2gmgGDnd
  public: pk_test_fl83c2XbpcmVD3MdRfUuwRqG

intercom:
  secret: 2Ycpgol1ZAeSnUqRfLTFxjHN4a7_aSRDLGADqVkO

raygun:
  django: vH1B+ZHR2AtBtkzyrK6twA==
