---
### Common ###

# Node.JS
nodejs_version: "4.4"
npm_enabled: yes
npm_packages:
  - name: webpack
  - name: webpack-dev-server
  - name: babel-cli
  - name: gulp
  - name: grunt-cli
  - name: bower
  - name: eslint

### Project ###

# Deploy
deploy_enabled: yes
deploy_app_name: kwhen
deploy_env: production

deploy_user: "{{deploy_app_name}}"
deploy_group: "{{deploy_user}}"

deploy_prefix: "/home/{{deploy_user}}"
deploy_dir: "{{deploy_prefix}}/{{deploy_app_name}}" # Main directory for deployment
deploy_etc_dir: "{{deploy_dir}}/etc"          # Directory where placed configuration files
deploy_log_dir: "{{deploy_dir}}/log"          # Directory where placed logs
deploy_run_dir: "{{deploy_dir}}/run"          # Directory where placed unix sockets and pid files
deploy_src_dir: "{{deploy_dir}}/src"          # Source's directory
deploy_bin_dir: "{{deploy_dir}}/bin"          # Directory where placed scripts

deploy_dir_skip: []

# Site
site_src_dir: '{{ deploy_src_dir }}'
