#Dev config used to handle options for development build
appPort: 7000
backendUrl: 'http://testing123.kwhen.com:3000'

certPath: './config/horizon-dev-cert.pem'
keyPath: './config/horizon-dev-key.pem'
