#Default config used to handle options for production build
appPort: 443
backendUrl: 'http://ec2-52-44-248-184.compute-1.amazonaws.com:3000'

certPath: '/etc/letsencrypt/live/prod.kwhen.com/cert.pem'
keyPath: '/etc/letsencrypt/live/prod.kwhen.com/privkey.pem'
sslChainPath: '/etc/letsencrypt/live/prod.kwhen.com/fullchain.pem'
