#Dev config used to handle options for development build
#http://testing123.kwhen.com:3000 7000
appPort: 7000
backendUrl: 'https://www.kwhen.com/api/' #TODO: update to local backend URL when local crawler setup is complete

certPath: './config/horizon-dev-cert.pem'
keyPath: './config/horizon-dev-key.pem'
