#General config used to handle general options for client (front-end)

mapbox:
  accessToken: 'pk.eyJ1Ijoia3doZW4iLCJhIjoiY2lnMmIxOWo5MWFpZHR1bTMzdDQ2OXI3bCJ9.dYs9YWilTsA-MwCD6HqTaQ'
  kwhenMapId: 'kwhen.cig2b17kj1ak8tjluug9gwvzv'

publicPath: '/api/'
