#Default config used to handle options for production build
appPort: 443
backendUrl: 'http://localhost:3000/'

certPath: '/etc/letsencrypt/live/staging.kwhen.com/cert.pem'
keyPath: '/etc/letsencrypt/live/staging.kwhen.com/privkey.pem'
sslChainPath: '/etc/letsencrypt/live/staging.kwhen.com/fullchain.pem'
