export const BOOTSTRAP = 'BOOTSTRAP';

export const REDIRECT = 'REDIRECT';

export const SET_META = 'SET_META';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ENABLE_FETCHER = 'ENABLE_FETCHER';
export const SET_USER = 'SET_USER';

export const PAGE_PREFIX = '@@page';

export function makeTriplet(name) {
  return [
    `${name}_START`,
    `${name}_SUCCESS`,
    `${name}_FAILURE`
  ];
}

export const FETCHER_TRIPLET = makeTriplet('FETCHER');
export const [FETCHER_START, FETCHER_SUCCESS, FETCHER_FAILURE] = FETCHER_TRIPLET;

export const CHAT_MESSAGES = 'CHAT_MESSAGES';
export const CHAT_SEND = 'CHAT_SEND';
export const CHAT_SEND_FILE = 'CHAT_SEND_FILE';
export const CHAT_UPLOAD_START = 'CHAT_UPLOAD_START';
export const CHAT_UPLOAD_COMPLETE = 'CHAT_UPLOAD_COMPLETE';
export const CHAT_SEND_START = 'CHAT_SEND_START';
export const CHAT_DELIVERED = 'CHAT_DELIVERED';
export const CHAT_OPEN = 'CHAT_OPEN';
export const CHAT_CLOSE = 'CHAT_CLOSE';
export const CHAT_MARK_READ = 'CHAT_MARK_READ';
export const CHAT_OPEN_EXTERNAL = 'CHAT_OPEN_EXTERNAL';
export const CHAT_ADD_FAVORITE = 'CHAT_ADD_FAVORITE';
export const CHAT_REMOVE_FAVORITE = 'CHAT_REMOVE_FAVORITE';
export const CHAT_ROSTER = 'CHAT_ROSTER';
export const CHAT_MESSAGE_ARRIVED = 'CHAT_MESSAGE_ARRIVED';

export const SHOW_ROSTER = 'SHOW_ROSTER';
export const HIDE_ROSTER = 'HIDE_ROSTER';

export const CHANGE_MODE_TRIPLET = makeTriplet('CHANGE_MODE');
export const [CHANGE_MODE_START, CHANGE_MODE_SUCCESS, CHANGE_MODE_FAILURE] = CHANGE_MODE_TRIPLET;

export const SET_SESSION = 'SET_SESSION';
export const API_REQUEST = 'API_REQUEST';

export const SUBJECT_REQUEST_ADD = 'SUBJECT_REQUEST_ADD';
export const SUBJECT_REQUEST_REMOVE = 'SUBJECT_REQUEST_REMOVE';

export const TUTOR_REQUEST_START = 'TUTOR_REQUEST_START';
export const TUTOR_REQUEST_ADD = 'TUTOR_REQUEST_ADD';
export const TUTOR_REQUEST_REMOVE = 'TUTOR_REQUEST_REMOVE';

export const PERSONAL_REQUEST_ADD = 'PERSONAL_REQUEST_ADD';
export const PERSONAL_REQUEST_REMOVE = 'PERSONAL_REQUEST_REMOVE';

export const REJECT_REQUEST = 'REJECT_REQUEST';
export const REJECTED_REQUEST_ADD = 'REJECTED_REQUEST_ADD';
export const REJECTED_REQUEST_REMOVE = 'REJECTED_REQUEST_REMOVE';
export const REJECTED_REQUEST_CLOSE = 'REJECTED_REQUEST_CLOSE';

export const BROADCAST_REQUEST_SHOW = 'BROADCAST_REQUEST_SHOW';
export const BROADCAST_REQUEST_HIDE = 'BROADCAST_REQUEST_HIDE';

export const PERSONAL_REQUEST_SHOW = 'PERSONAL_REQUEST_SHOW';
export const PERSONAL_REQUEST_HIDE = 'PERSONAL_REQUEST_HIDE';

export const PERSONAL_PROPOSAL_SHOW = 'PERSONAL_PROPOSAL_SHOW';
export const PERSONAL_PROPOSAL_HIDE = 'PERSONAL_PROPOSAL_HIDE';

export const PERSONAL_PROPOSAL_START = 'PERSONAL_PROPOSAL_START';

export const PERSONAL_PROPOSAL_ADD = 'PERSONAL_PROPOSAL_ADD';
export const PERSONAL_PROPOSAL_REMOVE = 'PERSONAL_PROPOSAL_REMOVE';

export const STUDENT_PROPOSAL_ADD = 'STUDENT_PROPOSAL_ADD';
export const STUDENT_PROPOSAL_REMOVE = 'STUDENT_PROPOSAL_REMOVE';

export const REJECTED_PROPOSAL_ADD = 'REJECTED_PROPOSAL_ADD';
export const REJECTED_PROPOSAL_REMOVE = 'REJECTED_PROPOSAL_REMOVE';

export const REJECTED_PROPOSAL_CLOSE = 'REJECTED_PROPOSAL_CLOSE';

export const PLAN_MODAL_SHOW = 'PLAN_MODAL_SHOW';
export const PLAN_MODAL_HIDE = 'PLAN_MODAL_HIDE';

export const CARD_MODAL_SHOW = 'CARD_MODAL_SHOW';
export const CARD_MODAL_HIDE = 'CARD_MODAL_HIDE';

export const APPLICATION_UNDER_REVIEW_MODAL_SHOW = 'APPLICATION_UNDER_REVIEW_MODAL_SHOW';
export const APPLICATION_UNDER_REVIEW_MODAL_HIDE = 'APPLICATION_UNDER_REVIEW_MODAL_HIDE';

export const ACCOUNT_SUSPENDED_MODAL_SHOW = 'ACCOUNT_SUSPENDED_MODAL_SHOW';
export const ACCOUNT_SUSPENDED_MODAL_HIDE = 'ACCOUNT_SUSPENDED_MODAL_HIDE';

export const LOAD_BILLING_INFO_TRIPLET = makeTriplet('LOAD_BILLING_INFO');
export const [LOAD_BILLING_INFO_START, LOAD_BILLING_INFO_SUCCESS, LOAD_BILLING_INFO_FAILURE] = LOAD_BILLING_INFO_TRIPLET;

export const SET_CARDS = 'SET_CARDS';
export const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
export const SET_HAS_SUBSCRIPTION = 'SET_HAS_SUBSCRIPTION';

export const CLOSE_MATCHING_BROADCASTS = 'CLOSE_MATCHING_BROADCASTS';

export const APP_START = 'APP_START';
export const APP_FINISH = 'APP_FINISH';
export const APP_TAB = 'APP_TAB';
export const APP_DRAW = 'APP_DRAW';
export const APP_ADD_DRAWS = 'APP_ADD_DRAWS';
export const APP_REMOVE_DRAWS = 'APP_REMOVE_DRAWS';
export const APP_SEND = 'APP_SEND';
export const APP_ADD_MESSAGES = 'APP_ADD_MESSAGES';
export const APP_ADD_DOCUMENTS = 'APP_ADD_DOCUMENTS';
export const APP_WHITEBOARDS = 'APP_WHITEBOARDS';
export const APP_SET_WHITEBOARD = 'APP_SET_WHITEBOARD';
export const APP_ADD_BOARD = 'APP_ADD_BOARD';
export const APP_CLEAR_BOARD = 'APP_CLEAR_BOARD';
export const APP_SET_VIDEO = 'APP_SET_VIDEO';
export const APP_SET_AUDIO = 'APP_SET_AUDIO';
export const APP_IGNORE_FIRST_TIME = 'APP_IGNORE_FIRST_TIME';

export const APP_PAUSE = 'APP_PAUSE';
export const APP_RESUME = 'APP_RESUME';
export const APP_END = 'APP_END';
export const APP_VOID = 'APP_VOID';
export const APP_VOID_REQUEST = 'APP_VOID_REQUEST';
export const APP_VOID_CANCEL = 'APP_VOID_CANCEL';
export const APP_LESSON_VOIDED_MODAL_HIDE = 'APP_LESSON_VOIDED_MODAL_HIDE';

export const APP_CONNECT_BILLING = 'APP_CONNECT_BILLING';
export const APP_DISCONNECT_BILLING = 'APP_DISCONNECT_BILLING';
export const APP_SET_BILLING_STATE = 'APP_SET_BILLING_STATE';

export const APP_UPLOAD = 'APP_UPLOAD';
export const APP_UPLOAD_TRIPLET = makeTriplet('APP_UPLOAD');
export const [APP_UPLOAD_START, APP_UPLOAD_SUCCESS, APP_UPLOAD_FAILURE] = APP_UPLOAD_TRIPLET;

export const TUTOR_VOIDED_LESSON_MODAL_SHOW = 'TUTOR_VOIDED_LESSON_MODAL_SHOW';
export const TUTOR_VOIDED_LESSON_MODAL_HIDE = 'TUTOR_VOIDED_LESSON_MODAL_HIDE';

export const AUTH_MODAL_SHOW = 'AUTH_MODAL_SHOW';
export const AUTH_MODAL_HIDE = 'AUTH_MODAL_HIDE';

export const FIREPAD_LOADED = 'FIREPAD_LOADED';
export const FIREPAD_FAILURE = 'FIREPAD_FAILURE';
export const LOAD_FIREPAD = 'LOAD_FIREPAD';

export const PAPERJS_LOADED = 'PAPERJS_LOADED';
export const PAPERJS_FAILURE = 'PAPERJS_FAILURE';
export const LOAD_PAPERJS = 'LOAD_PAPERJS';

export const TOKBOX_FAILURE = 'TOKBOX_FAILURE';
export const TOKBOX_LOADED = 'TOKBOX_LOADED';
export const LOAD_TOKBOX = 'LOAD_TOKBOX';
export const TOKBOX_UNSUPPORTED = 'TOKBOX_UNSUPPORTED';

export const TOAST_ADD = 'TOAST_ADD';
export const TOAST_REMOVE = 'TOAST_REMOVE';

export const SET_NEEDS_REVIEW = 'SET_NEEDS_REVIEW';

export const SET_APPLICATION_STEP = 'SET_APPLICATION_STEP';
export const FINISH_APPLICATION = 'FINISH_APPLICATION';
export const HIDE_APPLICATION_MODAL = 'HIDE_APPLICATION_MODAL';

export const BILLING_REQUIRED_SHOW = 'BILLING_REQUIRED_SHOW';
export const BILLING_REQUIRED_HIDE = 'BILLING_REQUIRED_HIDE';

export const FIREBASE_ONLINE = 'FIREBASE_ONLINE';

export const SHOW_PAYPAL_MODAL = 'SHOW_PAYPAL_MODAL';
export const HIDE_PAYPAL_MODAL = 'HIDE_PAYPAL_MODAL';

export const CONFIRM_NAVIGATION = 'CONFIRM_NAVIGATION';

export const CHAT_MINIMIZE = 'CHAT_MINIMIZE';
export const CHAT_MAXIMIZE = 'CHAT_MAXIMIZE';

export const DRAG_ENTER = 'DRAG_ENTER';
export const DRAG_LEAVE = 'DRAG_LEAVE';

export const SET_ROSTER_TAB = 'SET_ROSTER_TAB';

export const HOW_IT_WORKS_MODAL_SHOW = 'HOW_IT_WORKS_MODAL_SHOW';
export const HOW_IT_WORKS_MODAL_HIDE = 'HOW_IT_WORKS_MODAL_HIDE';

export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL';

////
export const HIDE_ALL_FORMS = 'HIDE_ALL_FORMS';
export const SWITCH_FORM = 'SWITCH_FORM';
export const SWITCH_MODAL = 'SWITCH_MODAL';
export const EDIT_WIDGET = 'EDIT_WIDGET';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';
export const ADD_WIDGET = 'ADD_WIDGET';
